name: Streamlit Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install streamlit
          
      - name: Create secrets.toml
        run: |
          mkdir -p .streamlit
          echo '[gcp_service_account]' > .streamlit/secrets.toml
          echo 'type = "${{ secrets.GCP_TYPE }}"' >> .streamlit/secrets.toml
          echo 'project_id = "${{ secrets.GCP_PROJECT_ID }}"' >> .streamlit/secrets.toml
          echo 'private_key_id = "${{ secrets.GCP_PRIVATE_KEY_ID }}"' >> .streamlit/secrets.toml
          echo 'private_key = "${{ secrets.GCP_PRIVATE_KEY }}"' >> .streamlit/secrets.toml
          echo 'client_email = "${{ secrets.GCP_CLIENT_EMAIL }}"' >> .streamlit/secrets.toml
          echo 'client_id = "${{ secrets.GCP_CLIENT_ID }}"' >> .streamlit/secrets.toml
          echo 'auth_uri = "${{ secrets.GCP_AUTH_URI }}"' >> .streamlit/secrets.toml
          echo 'token_uri = "${{ secrets.GCP_TOKEN_URI }}"' >> .streamlit/secrets.toml
          echo 'auth_provider_x509_cert_url = "${{ secrets.GCP_AUTH_PROVIDER_X509_CERT_URL }}"' >> .streamlit/secrets.toml
          echo 'client_x509_cert_url = "${{ secrets.GCP_CLIENT_X509_CERT_URL }}"' >> .streamlit/secrets.toml
          
      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: . 